name: Tests

on:
    pull_request:
        branches: [main]
        paths:
            - "src/**"
            - "package.json"
            - "yarn.lock"
            - "package-lock.json"
            - "jest.config.*"
            - ".github/workflows/tests.yml"
    push:
        branches-ignore: [main]

jobs:
    unit:
        name: unit-tests (node 20)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: Install deps
              run: |
                  if [ -f yarn.lock ]; then yarn install --frozen-lockfile; else npm ci; fi

            - name: Run tests
              run: |
                  if [ -f yarn.lock ]; then yarn test; else npm test; fi
